apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tomcat-logback
  namespace:  demo-tomcat
  labels:
    app: tomcat
    loghandler: logback
    target: demo
spec:
  selector:
    matchLabels:
      app: tomcat
      loghandler: logback
      target: demo
  replicas: 1 
  template:
    metadata:
      labels:
        app: tomcat
        loghandler: logback
        target: demo
    spec:
      containers:
      - name: tomcat
        image: eu.gcr.io/fausto-lab/tomcat-simple-site:logback-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - name: logback-configmap
          mountPath: "/usr/local/tomcat/lib/logback.xml"
          subPath: logback.xml
      volumes:
      - name: logback-configmap
        configMap:
          name: logback-config
          items:
          - key: logback.xml
            path: logback.xml
