apiVersion: v1
kind: Service
metadata:
  name: tomcat-logback
  namespace: demo-tomcat
spec:
  selector:
    app: tomcat
    loghandler: logback
    target: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: tomcat-http
  type: LoadBalancer
